name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    env:
      HUGO_VERSION: ${{ github.sha }}
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set git config core.quotepath false
        run: git config --global core.quotepath false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20"

      - name: Install theme
        run: cd themes/hugo-theme-luna && yarn install --production

      - name: Install postcss-cli
        run: npm install postcss-cli -g

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.113.0"
          extended: true

      - name: Build Hugo Site
        run: echo "HUGO_VERSION -> $HUGO_VERSION" && hugo --gc --minify --cleanDestinationDir

      - name: Preview Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODEREVIEWBLOG }}"
          projectId: codereviewblog
