name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Set git config core.quotepath false
        run: git config --global core.quotepath false

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Build theme
        run: cd themes/hugo-theme-luna && npm install postcss-cli -g && npm install --production

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo Site
        run: echo "HUGO_VERSION -> $HUGO_VERSION" && hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CODEREVIEWBLOG }}"
          channelId: live
          projectId: codereviewblog
